name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  IMAGE_NAME: aci-dash

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
